extends SceneTree
const World=preload("res://scripts/core/physics/physics_world_4d.gd")
const Session=preload("res://scripts/core/session_4d.gd")
const Box=preload("res://scripts/core/geometry/generators/tesseract.gd")
var failures:=0
func check(ok: bool,label: String):
	if not ok: failures+=1; push_error(label)
func _initialize():
	var w:=World.new()
	for i in range(2): check(w.configure_body(i,"dynamic",Vector4.ZERO,{"mass":1+3*i}),"Mass configuration")
	w.configure_body(2,"static",Vector4.ZERO)
	w.configure_body(3,"kinematic",Vector4.ONE)
	w.set_gravity(Vector4(0,-10,0,2))
	w.step(0.5)
	check(w.bodies[0][5]==-5 and w.bodies[1][5]==-5,"Gravity independent of mass")
	check(w.bodies[2][1]==0 and w.bodies[3][1]==0.5,"Gravity ignores static/kinematic")
	w.set_gravity(Vector4.ZERO)
	w.reset()
	w.apply_force(0,Vector4(4,0,0,0))
	w.apply_force(0,Vector4(4,0,0,0))
	w.apply_force(1,Vector4(8,0,0,0))
	var saved:=w.snapshot()
	w.step(0.5)
	check(w.bodies[0][4]==4 and w.bodies[1][4]==1,"Force accumulation / mass")
	w.step(0.5)
	check(w.bodies[0][4]==4,"Force consumed once")
	w.restore(saved)
	w.step(0.5)
	check(w.bodies[0][4]==4,"Restore pending force")
	check(saved[0][42]==8,"Snapshot independence")
	w.apply_impulse(1,Vector4(8,0,0,0))
	check(w.bodies[1][4]==3,"Impulse / mass without dt")
	check(not w.apply_force(2,Vector4.ONE) and not w.apply_impulse(3,Vector4.ONE),"Ownership enforced")
	check(w.set_kinematic_velocity(3,Vector4(0,0,0,7)),"Prescribe kinematic velocity")
	w.step(1)
	check(w.bodies[3][7]==7,"Kinematic prescription persists")
	check(not w.set_kinematic_velocity(0,Vector4.ZERO),"Cannot prescribe dynamic velocity")
	check(not w.configure_body(0,"dynamic",Vector4.ZERO,{"mass":0}),"Reject zero mass")
	check(not w.configure_body(0,"dynamic",Vector4.ZERO,{"mass":INF}),"Reject nonfinite mass")
	check(not w.configure_body(0,"dynamic",Vector4.ZERO,{"acceleration":Vector4.ONE}),"Acceleration removed")
	check(not w.apply_force(0,Vector4(NAN,0,0,0)),"Reject invalid force")
	var before:=w.snapshot()
	w.step(0)
	check(w.snapshot()==before,"Invalid dt preserves state")
	w.reset()
	check(w.bodies[0][4]==0 and w.bodies[0][42]==0,"Reset initial velocity and force")
	var s:=Session.new()
	var id:=s.add_geometry(Box.new())
	s.configure_body(id,"dynamic",Vector4.ZERO,{"mass":2})
	s.apply_force(id,Vector4(120,0,0,0))
	s.seek(1)
	check(absf(s.physics.bodies[id][4]-1)<1e-8,"Session force once")
	var end:=s.world_vertices(id)
	s.seek(0)
	s.seek(1)
	check(s.world_vertices(id)==end,"Recorded replay")
	s.seek(0.5)
	s.apply_impulse(id,Vector4(2,0,0,0))
	check(s.recording.frames.size()==31,"Input branches future history")
	s.seek(1)
	check(absf(s.physics.bodies[id][4]-2)<1e-8,"Branched impulse persists")
	s.invalidate()
	check(s.physics.bodies[id][4]==0,"Session reset discards runtime impulses")
	s.set_gravity(Vector4(0,0,0,2))
	s.seek(1)
	check(absf(s.physics.bodies[id][7]-2)<1e-8,"Session gravity")
	check(s.configure_dynamic_initial(id,{"velocity.0":"2"}),"Initial velocity expression compatibility")
	s.invalidate()
	check(s.physics.bodies[id][41]==2,"Reset keeps configured mass")
	print("Force failures: ",failures)
	quit(1 if failures else 0)
