extends SceneTree
const Session = preload("res://scripts/core/session_4d.gd")
const Box = preload("res://scripts/core/geometry/generators/tesseract.gd")
const Math4D = preload("res://scripts/core/math/transform_4d.gd")
var failures := 0
func check(ok: bool,label: String):
	if not ok: failures+=1; push_error(label)
func _initialize(): call_deferred("verify")
func verify():
	var session := Session.new()
	var parent := session.add_geometry(Box.new(),{}, {"position":{"W":"t"},"rotation":{"XY":"30*t"},"scale":"1+t"})
	session.configure_kinematic(parent)
	var child := session.add_geometry(Box.new(),{"position":{"X":"2+t"}}, {"position":{"Y":"3+t"}})
	session.configure_body(child,"static",Vector4.ZERO)
	check(session.reparent(child,parent,false),"Parent static")
	var initial := session.world_vertices(child)
	check(session.seek(1),"Advance static hierarchy")
	var parent_transform := Math4D.new()
	parent_transform.position.w=1
	parent_transform.scale=Vector4.ONE*2
	parent_transform.angles[0]=30
	var points := session.world_vertices(child)
	for i in range(points.size()): check((points[i]-Math4D.apply(parent_transform.matrix(),initial[i])).length()<1e-5,"Static inherits translation rotation scale with frozen local pose")
	check(session.reparent(child,0,true),"Unparent static preserving current pose")
	var unparented := session.world_vertices(child)
	session.seek(1)
	check(session.world_vertices(child)==unparented,"Unparented static fixed")
	var id := session.add_geometry(Box.new(),{"position":{"W":"t"}})
	check(session.set_range(2,5),"Nonzero run start")
	check(session.configure_dynamic_initial(id,{"velocity.0":"2*t", "angular_velocity.2":"15*t"}),"Configure initial expressions")
	check(session.physics.bodies[id][4]==4,"Evaluate at start")
	check(session.physics.bodies[id][26]==30,"Angular initial expressions")
	check(session.seek(3),"Simulate initialized rates")
	check(absf(session.physics.bodies[id][4]-4)<1e-8,"Velocity evolves rather than resampling")
	check(not session.configure_dynamic_initial(id,{"acceleration.0":"1"}),"Acceleration expressions removed")
	var end := session.world_vertices(id)
	session.seek(2.5)
	session.seek(3)
	check(session.world_vertices(id)==end,"Exact replay")
	session.invalidate()
	# Simulate a future interaction changing velocity/acceleration; no collision solver needed.
	session.physics.bodies[id][4]=100
	session.physics.apply_force(id,Vector4(7,0,0,0))
	session.physics.bodies[id][26]=80
	session.physics.step(0.5)
	check(session.physics.bodies[id][4]==103.5 and session.physics.bodies[id][26]==80,"Physics changes survive initial expressions")
	session.invalidate()
	check(session.physics.bodies[id][4]==4,"Reset restores initial expressions")
	check(session.set_range(3,5),"Change start time")
	check(session.physics.bodies[id][4]==6,"Start change re-evaluates")
	var saved: Dictionary=session.physics.snapshot()
	check(not session.configure_dynamic_initial(id,{"velocity.0":"sqrt(-1)"}),"Reject invalid initial expression")
	check(session.physics.snapshot()==saved,"Invalid edit is atomic")
	check(session.configure_dynamic_initial(id,{"velocity.0":"sqrt(t-2)"}),"Time-domain expression")
	check(not session.set_range(1,5) and session.playback.start==3,"Invalid start rejected atomically")
	check(session.configure_kinematic(id) and not session.initial_motion_tracks.has(id),"Switch mode clears initial driver")
	print("Initial condition failures: ",failures)
	quit(1 if failures else 0)
