extends SceneTree
const World=preload("res://scripts/core/physics/physics_world_4d.gd")
const Session=preload("res://scripts/core/session_4d.gd")
const Box=preload("res://scripts/core/geometry/generators/tesseract.gd")
var failures:=0
func check(ok: bool,label: String):
	if not ok: failures+=1; push_error(label)
func report(n: Vector4) -> Array:
	return [{"body_a":1,"body_b":2,"result":{"status":"intersecting","penetration":{"status":"penetrating","converged":true,"direction":PackedFloat64Array([n.x,n.y,n.z,n.w]),"depth":0.1}}}]
func _initialize():
	for restitution in [0.0,1.0]:
		var world:=World.new()
		world.configure_body(1,"dynamic",Vector4(2,3,0,0),{"mass":1.0,"restitution":restitution})
		world.configure_body(2,"dynamic",Vector4.ZERO,{"mass":3.0})
		var result=world.resolve_impulses(report(Vector4(1,0,0,0)))
		check(result.impulses==1,"One impulse")
		var a:=world.linear_velocity(1)
		var b:=world.linear_velocity(2)
		check(absf(a.x-(0.5-1.5*restitution))<1e-6 and absf(b.x-(0.5+0.5*restitution))<1e-6,"Analytic unequal mass response")
		check(a.y==3 and b.y==0,"Tangential velocity unchanged")
		check(absf(a.x+3*b.x-2)<1e-6,"Momentum conserved")
		if restitution==1: check(absf(a.x*a.x+3*b.x*b.x-4)<1e-6,"Elastic kinetic energy conserved")
		check(world.resolve_impulses(report(Vector4(1,0,0,0))).impulses==0,"No impulse for separating/stationary contact")
		var before=world.snapshot()
		check(not world.configure_body(1,"dynamic",Vector4.ZERO,{"restitution":2}),"Invalid restitution rejected")
		check(world.snapshot()==before,"Invalid config atomic")
	# Normal can point anywhere in R4, not only coordinate axes.
	var world:=World.new()
	var n:=Vector4(1,1,1,1).normalized()
	world.configure_body(1,"dynamic",n,{"restitution":1})
	world.configure_body(2,"static",Vector4.ZERO)
	world.resolve_impulses(report(n))
	check((world.linear_velocity(1)+n).length()<1e-6,"Oblique 4D reflection")
	var bad=report(n)
	bad[0].result.penetration.converged=false
	var before=world.snapshot()
	check(world.resolve_impulses(bad).skipped==1 and world.snapshot()==before,"Unconverged estimate ignored")
	world.configure_body(1,"dynamic",Vector4.ZERO)
	world.configure_body(2,"kinematic",-n*2)
	world.resolve_impulses(report(n))
	check((world.linear_velocity(1)+n*2).length()<1e-6 and world.linear_velocity(2)==-n*2,"Moving kinematic pushes dynamic")
	for restitution in [0.0,1.0]:
		var s:=Session.new()
		var a:=s.add_geometry(Box.new())
		var b:=s.add_geometry(Box.new(),{"position":{"W":2.05}})
		s.configure_body(a,"dynamic",Vector4(0,0,0,6),{"restitution":restitution})
		s.configure_body(b,"static",Vector4.ZERO)
		check(s.seek(1.0/60),"Session collision step")
		check(absf(s.physics.linear_velocity(a).w+6*restitution)<1e-5,"Session stop/bounce in W")
		check(s.physics.linear_velocity(b)==Vector4.ZERO,"Static unchanged")
		var saved=s.physics.snapshot()
		s.seek(0);s.seek(1.0/60)
		check(s.physics.snapshot()==saved,"Impulse replay exact")
		s.invalidate();s.seek(1.0/60)
		check(s.physics.snapshot()==saved,"Reset deterministic")
	# Track motion has no stored rate: adapter must derive prescribed translation.
	var s:=Session.new()
	var a:=s.add_geometry(Box.new())
	var b:=s.add_geometry(Box.new(),{"position":{"W":"2.05-6*t"}})
	s.configure_body(a,"dynamic",Vector4.ZERO)
	s.configure_kinematic(b)
	s.seek(1.0/60)
	check(absf(s.physics.linear_velocity(a).w+6)<0.001,"Track kinematic pushes using derived velocity")
	print("Impulse failures: ",failures)
	quit(1 if failures else 0)
